[component]
structures = ["content_blocks"]
label = "Services"
description = "Services section"
icon = "build"
tags = []

[props]
preheading = "Our Services"
heading = "We provide a wide range of creative services "

[[props.sections]]
title = "Web development"
icon = "ti-desktop"
content = "A digital agency isn't here to replace your internal team, we're here to partner."

[[props.sections]]
title = "Interface Design"
icon = "ti-layers"
content = "A digital agency isn't here to replace your internal team, we're here to partner."

[[props.sections]]
title = "Business Consulting"
icon = "ti-bar-chart"
content = "A digital agency isn't here to replace your internal team, we're here to partner."

[[props.sections]]
icon = "ti-vector"
title = "Branding"
content = "A digital agency isn't here to replace your internal team, we're here to partner."

[[props.sections]]
title = "App development"
icon = "ti-android"
content = "A digital agency isn't here to replace your internal team, we're here to partner."

[[props.sections]]
title = "Content creation"
icon = "ti-pencil-alt"
content = "A digital agency isn't here to replace your internal team, we're here to partner."