[component]
structures = ["content_blocks"]
label = "Hero"
description = "Hero block"
icon = "pending"
tags = []

[props]
title = "Hero page"
[props.hero]
title = "Hero"
background_image = "/images/bg/home-2.jpg"

