[component]
structures = ["content_blocks"]
label = "Portfolio"
description = "Portfolio section"
icon = "dns"
tags = []

[props]
preheading = "Our works"
heading = "We have done lots of works, lets check some"

[[props.projects]]
name = "Project California"
image_path = "/images/portfolio/1.jpg"
type = "Web Development"

[[props.projects]]
name = "Project California"
image_path = "/images/portfolio/2.jpg"
type = "Web Development"

[[props.projects]]
name = "Project California"
image_path = "/images/portfolio/3.jpg"
type = "Web Development"

[[props.projects]]
name = "Project California"
image_path = "/images/portfolio/4.jpg"
type = "Web Development"

[[props.projects]]
name = "Project California"
image_path = "/images/portfolio/5.jpg"
type = "Web Development"

[[props.projects]]
name = "Project California"
image_path = "/images/portfolio/6.jpg"
type = "Web Development"