[component]
structures = ["content_blocks"]
label = "Intro"
description = "Overview section"
icon = "receipt"
tags = []

[props]
preheading = "We are creative & expert people"
heading = "We work with business & provide solution to client with their business problem"

[[props.sections]]
title = "Modern & Responsive design"
icon = "ti-desktop"
content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit, ducimus."

[[props.sections]]
title = "Awarded licensed company"
icon = "ti-medall"
content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit, ducimus."

[[props.sections]]
title = "Build your website Professionally"
icon = "ti-layers"
content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit, ducimus."